apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oulahn-webapp
  labels:
    app: oulahn-webapp
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oulahn-webapp
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50